### ISSUE TITLE
Usage with material theme

### ISSUE THREAD

**Issue by OSchwark** [appreciated/card#4]
Thanks a lot for this nice addon!
What would be necessary to get this running using material theme in vaadin? It works but for example doesn't show the shadow
Lumo
![grafik](https://user-images.githubusercontent.com/8201232/58256344-20fffd00-7d6f-11e9-9f40-8f652bd4e33c.png)
Material
![grafik](https://user-images.githubusercontent.com/8201232/58256365-2bba9200-7d6f-11e9-929f-5742d7488464.png)

Thanks a lot for any help!
Olli

**Comment by appreciated** [comment]
Fixed by 83ea485f858f7e703bca6fb97e5eff004f1516ef
