### ISSUE TITLE
upgrade to npm

### ISSUE THREAD

**Issue by berndhopp** [appreciated/card#8]

**Comment by appreciated** [comment]
Can you elaborate on what you mean by this?

**Comment by berndhopp** [comment]
Sorry, dachte das wäre klar. Es müsste,  soweit ich sehen kann, bei allen Komponenten von appreciated ein mvn vaadin:upgrade-to-p3 ausgeführt werden,  damit diese in vaadin 14+ ohne Kompatibilitätsmodus verwendet  werden können.

**Comment by appreciated** [comment]
Die Komponenten wurden schon händisch auf Polymer 3 geupgradet. Bedarf das noch weiteren Anpassungen?

**Comment by berndhopp** [comment]
Meinem Verständnis nach fehlten noch die @npm annotations, zumindest funktioniert bei mir alles nur im Kompatibilitätsmodus

**Comment by appreciated** [comment]
Also da dieses Addon keine Npm Abhängigkeiten hat (die JS Dateien sind alle im Projekt) sind denke ich zumindest keine Annotationen notwendig.
Gibt es eine Fehlermeldung?

**Comment by berndhopp** [comment]
Ja, ich hab es gerade gesehen mit den js Dateien. Zumindest funktioniert die Komponente für mich nicht mit vaadin 15 Beta 1, ich sehe im dom nur das leere Element ohne shadow dom, also scheint der Browser die js Dateien nicht zu ziehen. Ich bin gerade nicht zuhause und habe keinen Computer hier,  aber ich vermute dass die Sample Projekte auch mit v15 nicht mehr laufen

**Comment by berndhopp** [comment]
![image](https://user-images.githubusercontent.com/1919315/75196654-bbf19180-575c-11ea-99ff-356fbc6b0755.png)

**Comment by appreciated** [comment]
Also ich würde mal ausprobieren ob [folgendes](https://github.com/vaadin/flow/issues/6036#issuecomment-536986765) hilft, ansonsten gehe ich davon aus, das es entweder ein Vaadin 15 Bug ist, oder dass an dem JS Ressourcen Management etwas geändert wurde.

**Comment by berndhopp** [comment]
hat bei mir nicht funktioniert, ich warte mal den RC ab und gucke ob es dann noch auftrittt

**Comment by berndhopp** [comment]
es scheint ein spring boot problem zu sein, ich bekomme denselben fehler wenn ich ein neues starter projekte mit spring boot von vaadin.com herunterlade, die dependency zu card hinzufüge und eine card im defaultview einfüge.

https://github.com/berndhopp/spring_boot_appreciated_not_working

**Comment by berndhopp** [comment]
![image](https://user-images.githubusercontent.com/1919315/75882531-a8f85480-5e21-11ea-87a9-af4c4e4ed863.png)

**Comment by appreciated** [comment]
Also da es unter Vaadin 14 geht würde ich auf einen Vaadin Spring oder Vaadin Bug spekulieren.

**Comment by berndhopp** [comment]
since it is established this is a vaadin bug, I'm gonna close this issue

**Comment by appreciated** [comment]
No too sure it is but, we will see.
